// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file contact.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file contact.proto.
 */
export const file_contact: GenFile = /*@__PURE__*/
  fileDesc("Cg1jb250YWN0LnByb3RvIvMBCg9XQ0NvbnRhY3RSZW1hcmsSFQoIbmlja25hbWUYASABKAlIAIgBARIKCgJpZBgCIAEoCRITCgZyZW1hcmsYAyABKAlIAYgBARIZCgxyZW1hcmtQaW55aW4YBCABKAlIAogBARIeChFyZW1hcmtQaW55aW5Jbml0cxgFIAEoCUgDiAEBEhsKDm5pY2tuYW1lUGlueWluGAYgASgJSASIAQFCCwoJX25pY2tuYW1lQgkKB19yZW1hcmtCDwoNX3JlbWFya1BpbnlpbkIUChJfcmVtYXJrUGlueWluSW5pdHNCEQoPX25pY2tuYW1lUGlueWluImoKEldDQ29udGFjdEhlYWRJbWFnZRIbCg5oZWFkSW1hZ2VUaHVtYhgCIAEoCUgAiAEBEhYKCWhlYWRJbWFnZRgDIAEoCUgBiAEBQhEKD19oZWFkSW1hZ2VUaHVtYkIMCgpfaGVhZEltYWdlIoEBChBXQ0NvbnRhY3RQcm9maWxlEhMKC3Byb2ZpbGVGbGFnGAEgASgFEhYKDnByb2ZpbGVDb3VudHJ5GAIgASgJEhcKD3Byb2ZpbGVQcm92aW5jZRgDIAEoCRITCgtwcm9maWxlQ2l0eRgEIAEoCRISCgpwcm9maWxlQmlvGAUgASgJIlUKD1dDQ29udGFjdFNvY2lhbBIYChBzb2NpYWxCYWNrZ3JvdW5kGAkgASgJEhgKC3NvY2lhbFBob25lGAsgASgJSACIAQFCDgoMX3NvY2lhbFBob25lIpQBChFXQ0NvbnRhY3RDaGF0Um9vbRIZChFjaGF0cm9vbU1lbWJlcklkcxgBIAEoCRIYChBjaGF0cm9vbU93bmVySWRzGAIgASgJEhkKEWNoYXRyb29tYU1heENvdW50GAQgASgNEhcKD2NoYXRyb29tVmVyc2lvbhgFIAEoDRIWCg5jaGF0cm9vbU1lbWJlchgGIAEoCSJFCg9XQ0NvbnRhY3RPcGVuSU0SGQoRb3BlbklNQ29udGFjdEluZm8YASABKAkSFwoPb3BlbklNQ29udGFjdElkGAIgASgJYgZwcm90bzM");

/**
 * @generated from message WCContactRemark
 */
export type WCContactRemark = Message<"WCContactRemark"> & {
  /**
   * @generated from field: optional string nickname = 1;
   */
  nickname?: string;

  /**
   * @generated from field: string id = 2;
   */
  id: string;

  /**
   * @generated from field: optional string remark = 3;
   */
  remark?: string;

  /**
   * @generated from field: optional string remarkPinyin = 4;
   */
  remarkPinyin?: string;

  /**
   * @generated from field: optional string remarkPinyinInits = 5;
   */
  remarkPinyinInits?: string;

  /**
   * string field7 = 7;
   * string field8 = 8;
   *
   * @generated from field: optional string nicknamePinyin = 6;
   */
  nicknamePinyin?: string;
};

/**
 * Describes the message WCContactRemark.
 * Use `create(WCContactRemarkSchema)` to create a new message.
 */
export const WCContactRemarkSchema: GenMessage<WCContactRemark> = /*@__PURE__*/
  messageDesc(file_contact, 0);

/**
 * @generated from message WCContactHeadImage
 */
export type WCContactHeadImage = Message<"WCContactHeadImage"> & {
  /**
   * int32 headImageFlag = 1; // 我不知道我怎么知道这个字段叫 flag 以及有什么用
   *
   * @generated from field: optional string headImageThumb = 2;
   */
  headImageThumb?: string;

  /**
   * string field4 = 4;
   *
   * @generated from field: optional string headImage = 3;
   */
  headImage?: string;
};

/**
 * Describes the message WCContactHeadImage.
 * Use `create(WCContactHeadImageSchema)` to create a new message.
 */
export const WCContactHeadImageSchema: GenMessage<WCContactHeadImage> = /*@__PURE__*/
  messageDesc(file_contact, 1);

/**
 * @generated from message WCContactProfile
 */
export type WCContactProfile = Message<"WCContactProfile"> & {
  /**
   * 我不知道我怎么知道这个字段叫 flag 以及有什么用
   *
   * @generated from field: int32 profileFlag = 1;
   */
  profileFlag: number;

  /**
   * @generated from field: string profileCountry = 2;
   */
  profileCountry: string;

  /**
   * @generated from field: string profileProvince = 3;
   */
  profileProvince: string;

  /**
   * @generated from field: string profileCity = 4;
   */
  profileCity: string;

  /**
   * @generated from field: string profileBio = 5;
   */
  profileBio: string;
};

/**
 * Describes the message WCContactProfile.
 * Use `create(WCContactProfileSchema)` to create a new message.
 */
export const WCContactProfileSchema: GenMessage<WCContactProfile> = /*@__PURE__*/
  messageDesc(file_contact, 2);

/**
 * @generated from message WCContactSocial
 */
export type WCContactSocial = Message<"WCContactSocial"> & {
  /**
   * string field1 = 1;
   * string field2 = 2;
   * int32 field3 = 3;
   * int32 field7 = 7;
   * int32 field8 = 8;
   *
   * @generated from field: string socialBackground = 9;
   */
  socialBackground: string;

  /**
   * string field10 = 10;
   *
   * string field12 = 12;
   *
   * @generated from field: optional string socialPhone = 11;
   */
  socialPhone?: string;
};

/**
 * Describes the message WCContactSocial.
 * Use `create(WCContactSocialSchema)` to create a new message.
 */
export const WCContactSocialSchema: GenMessage<WCContactSocial> = /*@__PURE__*/
  messageDesc(file_contact, 3);

/**
 * @generated from message WCContactChatRoom
 */
export type WCContactChatRoom = Message<"WCContactChatRoom"> & {
  /**
   * @generated from field: string chatroomMemberIds = 1;
   */
  chatroomMemberIds: string;

  /**
   * @generated from field: string chatroomOwnerIds = 2;
   */
  chatroomOwnerIds: string;

  /**
   * 这应该也是我猜的
   *
   * @generated from field: uint32 chatroomaMaxCount = 4;
   */
  chatroomaMaxCount: number;

  /**
   * 我不知道我为什么知道这个字段叫 version
   *
   * @generated from field: uint32 chatroomVersion = 5;
   */
  chatroomVersion: number;

  /**
   * xml
   *
   * @generated from field: string chatroomMember = 6;
   */
  chatroomMember: string;
};

/**
 * Describes the message WCContactChatRoom.
 * Use `create(WCContactChatRoomSchema)` to create a new message.
 */
export const WCContactChatRoomSchema: GenMessage<WCContactChatRoom> = /*@__PURE__*/
  messageDesc(file_contact, 4);

/**
 * @generated from message WCContactOpenIM
 */
export type WCContactOpenIM = Message<"WCContactOpenIM"> & {
  /**
   * json
   *
   * @generated from field: string openIMContactInfo = 1;
   */
  openIMContactInfo: string;

  /**
   * @generated from field: string openIMContactId = 2;
   */
  openIMContactId: string;
};

/**
 * Describes the message WCContactOpenIM.
 * Use `create(WCContactOpenIMSchema)` to create a new message.
 */
export const WCContactOpenIMSchema: GenMessage<WCContactOpenIM> = /*@__PURE__*/
  messageDesc(file_contact, 5);

