// @generated by protoc-gen-es v2.7.0 with parameter "target=ts"
// @generated from file sticker-message-description.proto (syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file sticker-message-description.proto.
 */
export const file_sticker_message_description: GenFile = /*@__PURE__*/
  fileDesc("CiFzdGlja2VyLW1lc3NhZ2UtZGVzY3JpcHRpb24ucHJvdG8iTQoZU3RpY2tlck1lc3NhZ2VEZXNjcmlwdGlvbhIwCgdlbnRyaWVzGAEgAygLMh8uU3RpY2tlck1lc3NhZ2VEZXNjcmlwdGlvbkVudHJ5Ij4KHlN0aWNrZXJNZXNzYWdlRGVzY3JpcHRpb25FbnRyeRIOCgZsb2NhbGUYASABKAkSDAoEdGV4dBgCIAEoCWIGcHJvdG8z");

/**
 * @generated from message StickerMessageDescription
 */
export type StickerMessageDescription = Message<"StickerMessageDescription"> & {
  /**
   * @generated from field: repeated StickerMessageDescriptionEntry entries = 1;
   */
  entries: StickerMessageDescriptionEntry[];
};

/**
 * Describes the message StickerMessageDescription.
 * Use `create(StickerMessageDescriptionSchema)` to create a new message.
 */
export const StickerMessageDescriptionSchema: GenMessage<StickerMessageDescription> = /*@__PURE__*/
  messageDesc(file_sticker_message_description, 0);

/**
 * @generated from message StickerMessageDescriptionEntry
 */
export type StickerMessageDescriptionEntry = Message<"StickerMessageDescriptionEntry"> & {
  /**
   * @generated from field: string locale = 1;
   */
  locale: string;

  /**
   * @generated from field: string text = 2;
   */
  text: string;
};

/**
 * Describes the message StickerMessageDescriptionEntry.
 * Use `create(StickerMessageDescriptionEntrySchema)` to create a new message.
 */
export const StickerMessageDescriptionEntrySchema: GenMessage<StickerMessageDescriptionEntry> = /*@__PURE__*/
  messageDesc(file_sticker_message_description, 1);

